name: Build, Test, Push Image, Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  WEBAPP_NAME: Docker     

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps for tests (Torch CPU first)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --index-url https://download.pytorch.org/whl/cpu torch==2.8.0+cpu
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Lowercase image name
        run: echo "IMAGE_NAME_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: test-build-push

    steps:
      - name: Recompute lowercase image name
        run: |
          echo "IMAGE_NAME_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "IMAGE_REF=${{ env.REGISTRY }}/${IMAGE_NAME_LC}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_REF }}

